### Creates a  NEW PATIENT
POST http://localhost:4004/api/patients
Content-Type: application/json

{
  "name": "Yo Bala",
  "email": "Bala@gmail.com",
  "address": "Bala Nagar it Nagar",
  "dateOfBirth": "1995-05-05",
  "registeredDate": "2025-03-20"
}

###