### UPDATES An existing PATIENT
PUT http://localhost:4000/patients/bd00ac58-1f03-4d28-8cc7-5e0d47240519
Content-Type: application/json

{
  "name": "Paritosh PAL",
  "email": "paritoshPal@gmail.com",
  "address": "Apeksha Nagar Wadgaon Road Chandrapur",
  "dateOfBirth": "2000-05-05"
}

###